services:
  redis:
    image: redis
    container_name: Docsphere-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  qdrant:
    image: qdrant/qdrant:latest
    container_name: Docsphere-qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
